###
GET http://{{host}}/api/note/index
Access-Token: {{accessToken}}

###
POST http://{{host}}/note/get
Content-Type: application/json
Access-Token: {{accessToken}}

{
    "path": "C:\\test\\note\\note1.md"
}

###
POST http://{{host}}/note/save
Content-Type: application/json
Access-Token: {{accessToken}}

{
  "path": "C:\\test\\note\\note1.md",
  "content": "test"
}


