###
GET http://{{host}}/notes
Access-Token: {{accessToken}}

###
POST http://{{host}}/note
Content-Type: application/json
Access-Token: {{accessToken}}

{
    "path": "C:\\test\\note\\note1.md"
}

###
POST http://{{host}}/save
Content-Type: application/json
Access-Token: {{accessToken}}

{
  "path": "C:\\test\\note\\note1.md",
  "content": "test"
}


