### 登录
POST http://{{host}}/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 获取笔记提醒计划任务
GET http://{{host}}/api/remind/cron
Access-Token: {{accessToken}}




