### 登录
< {%
    client.global.clearAll();
%}
POST http://{{host}}/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

> {%
    client.global.set('accessToken', response.body.data.accessToken);
%}

### GET获取笔记内容，非法绝对路径
GET http://{{host}}/api/note/get?path=C%3A%5Ctest%5Ctest.md
Access-Token: {{accessToken}}

### POST获取笔记内容，非法绝对路径
POST http://{{host}}/api/note/get
Content-Type: application/json
Access-Token: {{accessToken}}

{
  "path": "C:\\test\\test.md"
}

### GET获取笔记内容，非法笔记根路径以外路径
GET http://{{host}}/api/note/get?path=..%5Ctest.md
Access-Token: {{accessToken}}

### POST获取笔记内容，非法笔记根路径以外路径
POST http://{{host}}/api/note/get
Content-Type: application/json
Access-Token: {{accessToken}}

{
  "path": "..\\test.md"
}





