### 登录
< {%
    client.global.clearAll();
%}
POST http://{{host}}/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

> {%
    client.global.set('accessToken', response.body.data.accessToken);
    client.global.set('content', new Date().toISOString());
%}

### 保存笔记内容
POST http://{{host}}/api/explore/save-content
Content-Type: application/json
Access-Token: {{accessToken}}

{
  "path": "\\test.md",
  "content": "{{content}}"
}

